import React, { useEffect, useState } from 'react';
import { Bell, Check, Plus, Target, Minus, Archive, CalendarClock } from 'lucide-react';
export default function Planner({ productiveSeconds=0, section='all' }) {
  const [data,setData]=useState({reminders:[],goals:[]});
  const [title,setTitle]=useState(''),[scheduled,setScheduled]=useState(false),[due,setDue]=useState('');
  const [goalTitle,setGoalTitle]=useState(''),[kind,setKind]=useState('steps'),[target,setTarget]=useState(5);
  const [showDone,setShowDone]=useState(false),[showArchived,setShowArchived]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const desktop=Boolean(window.purrductive?.getPlanner);
  useEffect(()=>{if(!desktop)return;let active=true;const refresh=()=>window.purrductive.getPlanner().then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e.message);});refresh();const unsubscribe=window.purrductive.onPlannerChanged(refresh);return()=>{active=false;unsubscribe();};},[]);
  async function change(action) {if(!desktop||busy)return false;setBusy(true);try{setData(await window.purrductive.changePlanner(action));setError('');return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
  const reminders=data.reminders.filter(r=>showDone||!r.done).slice().sort((a,b)=>Number(a.done)-Number(b.done)||(a.dueAt||'z').localeCompare(b.dueAt||'z'));
  return <section className={'planner-grid planner-view-'+section} aria-label={section==='all'?'Reminders and goals':section}>
    <article className="planner-card reminders-card"><header><span className="planner-stamp"><Bell size={21}/></span><div><p className="eyebrow">LITTLE THINGS, REMEMBERED</p><h2>A note from you, to you.</h2></div><span className="planner-count">{data.reminders.filter(r=>!r.done).length}</span></header>
      {!desktop && <p className="planner-help">Create reminders on your laptop. They stay on that device; cloud sync currently covers activity history only.</p>}
      <form onSubmit={async e=>{e.preventDefault();let dueAt=null;if(scheduled){if(!due){setError('Choose a date and time.');return;}dueAt=new Date(due).toISOString();}if(await change({type:'addReminder',title,dueAt})){setTitle('');setDue('');setScheduled(false);}}}>
        <label className="sr-only" htmlFor="reminder-title">Reminder title</label><input id="reminder-title" maxLength={180} required placeholder="Drink water, send that email, call mum…" value={title} onChange={e=>setTitle(e.target.value)} disabled={!desktop}/>
        <div className="planner-form-row"><label className="schedule-switch"><input type="checkbox" checked={scheduled} onChange={e=>setScheduled(e.target.checked)} disabled={!desktop}/><CalendarClock size={14}/> Set date & time</label><button type="submit" disabled={!desktop||busy||!title.trim()}><Plus size={15}/> Pin it</button></div>
        {scheduled && <input type="datetime-local" aria-label="Reminder date and time" required value={due} onChange={e=>setDue(e.target.value)}/>}
      </form>
      <div className="pinned-reminders">{reminders.map(row=><div className={'pinned-note '+(row.done?'is-done ':'')+(!row.done&&row.dueAt&&Date.parse(row.dueAt)<=Date.now()?'is-due':'')} key={row.id}><button className="note-check" aria-label={(row.done?'Reopen ':'Complete ')+row.title} aria-pressed={row.done} disabled={busy} onClick={()=>change({type:'toggleReminder',id:row.id})}>{row.done&&<Check size={16}/>}</button><div><strong>{row.title}</strong><small>{row.dueAt ? new Date(row.dueAt).toLocaleString() : 'No deadline. Here until you tick it.'}</small>{!row.done&&row.dueAt&&Date.parse(row.dueAt)<=Date.now()&&<span className="due-label">Due · waiting for your tick</span>}</div></div>)}</div>
      {!reminders.length&&<p className="planner-empty">A little space for what’s on your mind.</p>}
      <button className="text-button" onClick={()=>setShowDone(!showDone)}>{showDone?'Hide':'Show'} completed ({data.reminders.filter(r=>r.done).length})</button><p className="planner-help">Scheduled alerts need Purrductive running (the tray is fine). Windows notification settings may silence alerts; due notes stay here.</p>
    </article>
    <article className="planner-card goals-card"><header><span className="planner-stamp"><Target size={21}/></span><div><p className="eyebrow">ONE SMALL STEP</p><h2>Something to grow toward.</h2></div></header>
      <form onSubmit={async e=>{e.preventDefault();if(await change({type:'addGoal',title:goalTitle,kind,target})){setGoalTitle('');}}}><label className="sr-only" htmlFor="goal-title">Goal title</label><input id="goal-title" maxLength={180} required placeholder="What would you like to work toward?" value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} disabled={!desktop}/><div className="planner-goal-inputs"><select aria-label="Goal type" value={kind} onChange={e=>{setKind(e.target.value);setTarget(e.target.value==='productive'?120:5);}} disabled={!desktop}><option value="steps">Manual steps</option><option value="productive">Daily productive minutes</option></select><input aria-label="Goal target" type="number" min="1" max="10000" required value={target} onChange={e=>setTarget(e.target.value)} disabled={!desktop}/><button disabled={!desktop||busy||!goalTitle.trim()}><Plus size={15}/> Add</button></div></form>
      {data.goals.filter(g=>showArchived||!g.archived).map(goal=>{const progress=goal.kind==='productive'?Math.floor(productiveSeconds/60):goal.progress;const percent=Math.min(100,progress/goal.target*100);return <div className={'goal-note '+(goal.archived?'archived':'')} key={goal.id}><div className="goal-title"><strong>{goal.title}</strong><button title={goal.archived?'Restore goal':'Archive goal'} aria-label={(goal.archived?'Restore ':'Archive ')+goal.title} disabled={busy} onClick={()=>change({type:'archiveGoal',id:goal.id})}><Archive size={14}/></button></div><div className="goal-progress" role="progressbar" aria-label={goal.title} aria-valuemin={0} aria-valuemax={goal.target} aria-valuenow={Math.min(progress,goal.target)}><i style={{width:percent+'%'}}/></div><div className="goal-bottom"><span>{progress} / {goal.target} {goal.kind==='productive'?'min today on this laptop':'steps'} {progress>=goal.target?'✓':''}</span>{goal.kind==='steps'&&!goal.archived&&<div><button aria-label={'Remove a step from '+goal.title} disabled={busy||progress<=0} onClick={()=>change({type:'goalProgress',id:goal.id,delta:-1})}><Minus size={14}/></button><button aria-label={'Add a step to '+goal.title} disabled={busy||progress>=goal.target} onClick={()=>change({type:'goalProgress',id:goal.id,delta:1})}><Plus size={14}/></button></div>}</div></div>;})}
      {!data.goals.length&&<p className="planner-empty">Big plans welcome. Tiny steps count.</p>}<button className="text-button" onClick={()=>setShowArchived(!showArchived)}>{showArchived?'Hide':'Show'} archived goals</button><p className="planner-help">Daily time goals use today’s recorded productive time, regardless of the dashboard date. Manual steps stay until you change them.</p>
    </article>{error&&<p className="planner-error" role="alert">{error}</p>}
  </section>;
}
